# ####################################################################

#  Created by Genus(TM) Synthesis Solution 22.13-s093_1 on Tue Jul 08 21:30:31 EEST 2025

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design mod_flip_flop

create_clock -name "clk" -period 13.0 -waveform {0.0 6.5} [get_ports clk]
set_load -pin_load 0.002 [get_ports {remainder[5]}]
set_load -pin_load 0.002 [get_ports {remainder[4]}]
set_load -pin_load 0.002 [get_ports {remainder[3]}]
set_load -pin_load 0.002 [get_ports {remainder[2]}]
set_load -pin_load 0.002 [get_ports {remainder[1]}]
set_load -pin_load 0.002 [get_ports {remainder[0]}]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports rst]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {A[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {B[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {remainder[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {remainder[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {remainder[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {remainder[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {remainder[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.02 [get_ports {remainder[0]}]
