
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Jul  8 2025 17:28:51 EEST (Jul  8 2025 14:28:51 UTC)

// Verification Directory fv/mod_flip_flop 

module mod15_n32(A, B, remainder);
  input [31:0] A, B;
  output [3:0] remainder;
  wire [31:0] A, B;
  wire [3:0] remainder;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  OAI211X1 g5322__2398(.A0 (n_202), .A1 (n_217), .B0 (n_222), .C0
       (n_223), .Y (remainder[1]));
  OAI221X1 g5323__5107(.A0 (n_209), .A1 (n_210), .B0 (n_207), .B1
       (n_214), .C0 (n_221), .Y (remainder[2]));
  OAI222X1 g5324__6260(.A0 (n_198), .A1 (n_13), .B0 (n_196), .B1
       (n_216), .C0 (n_197), .C1 (n_212), .Y (remainder[0]));
  MXI2XL g5325__4319(.A (n_220), .B (n_219), .S0 (n_193), .Y
       (remainder[3]));
  OAI2BB1X1 g5326__8428(.A0N (n_197), .A1N (n_215), .B0 (n_204), .Y
       (n_223));
  OAI2BB1X1 g5327__5526(.A0N (n_196), .A1N (n_213), .B0 (n_205), .Y
       (n_222));
  NAND2X1 g5328__6783(.A (n_207), .B (n_218), .Y (n_221));
  AOI2BB1X1 g5329__3680(.A0N (n_203), .A1N (n_214), .B0 (n_206), .Y
       (n_220));
  AOI2BB1X1 g5330__1617(.A0N (n_206), .A1N (n_211), .B0 (n_203), .Y
       (n_219));
  OAI31X1 g5331__2802(.A0 (n_193), .A1 (n_10), .A2 (n_204), .B0
       (n_211), .Y (n_218));
  OA21X1 g5332__1705(.A0 (n_9), .A1 (n_209), .B0 (n_197), .Y (n_217));
  OA21X1 g5333__5122(.A0 (n_11), .A1 (n_12), .B0 (n_209), .Y (n_216));
  AOI32X1 g5334__8246(.A0 (n_193), .A1 (n_195), .A2 (n_207), .B0
       (n_199), .B1 (n_208), .Y (n_215));
  NAND2X1 g5335__7098(.A (n_197), .B (n_12), .Y (n_213));
  AOI21X1 g5336__6131(.A0 (n_10), .A1 (n_202), .B0 (n_204), .Y (n_214));
  AOI22X1 g5338__1881(.A0 (n_199), .A1 (n_202), .B0 (n_195), .B1
       (n_205), .Y (n_210));
  OAI21X1 g5339__5115(.A0 (n_206), .A1 (n_202), .B0 (n_208), .Y
       (n_212));
  OA21X1 g5340__7482(.A0 (n_196), .A1 (n_204), .B0 (n_202), .Y (n_211));
  NAND2X1 g5341__4733(.A (n_193), .B (n_206), .Y (n_209));
  NOR2BX1 g5343__6161(.AN (n_193), .B (n_203), .Y (n_208));
  ADDHX1 g5345__9315(.A (n_191), .B (n_200), .CO (n_206), .S (n_207));
  ADDHX1 g5346__9945(.A (n_185), .B (n_201), .CO (n_204), .S (n_205));
  NOR2X1 g5347__2883(.A (n_191), .B (n_200), .Y (n_203));
  OR2X1 g5348__2346(.A (n_185), .B (n_201), .Y (n_202));
  ADDFX1 g5349__1666(.A (n_121), .B (n_188), .CI (n_194), .CO (n_200),
       .S (n_201));
  ADDHX1 g5350__7410(.A (n_175), .B (n_8), .CO (n_199), .S (n_198));
  NAND2X1 g5352__6417(.A (n_175), .B (n_195), .Y (n_197));
  OR2X1 g5354__5477(.A (n_175), .B (n_195), .Y (n_196));
  ADDFX1 g5356__2398(.A (n_122), .B (n_189), .CI (n_192), .CO (n_194),
       .S (n_195));
  ADDFX1 g5357__5107(.A (n_117), .B (n_187), .CI (n_190), .CO (n_192),
       .S (n_193));
  ADDFX1 g5358__6260(.A (n_113), .B (n_183), .CI (n_184), .CO (n_190),
       .S (n_191));
  ADDFX1 g5359__4319(.A (n_152), .B (n_180), .CI (n_186), .CO (n_188),
       .S (n_189));
  ADDFX1 g5360__8428(.A (n_153), .B (n_181), .CI (n_182), .CO (n_186),
       .S (n_187));
  ADDFX1 g5361__5526(.A (n_104), .B (n_174), .CI (n_179), .CO (n_184),
       .S (n_185));
  ADDFX1 g5362__6783(.A (n_143), .B (n_177), .CI (n_178), .CO (n_182),
       .S (n_183));
  ADDFX1 g5363__3680(.A (n_148), .B (n_163), .CI (n_176), .CO (n_180),
       .S (n_181));
  ADDFX1 g5364__1617(.A (n_138), .B (n_170), .CI (n_173), .CO (n_178),
       .S (n_179));
  ADDFX1 g5365__2802(.A (n_151), .B (n_169), .CI (n_172), .CO (n_176),
       .S (n_177));
  ADDHX1 g5366__1705(.A (n_90), .B (n_171), .CO (n_174), .S (n_175));
  ADDFX1 g5367__5122(.A (n_149), .B (n_167), .CI (n_166), .CO (n_172),
       .S (n_173));
  ADDHX1 g5368__8246(.A (n_134), .B (n_168), .CO (n_170), .S (n_171));
  AO22X1 g5369__7098(.A0 (n_161), .A1 (n_160), .B0 (n_159), .B1
       (n_165), .Y (n_169));
  ADDHX1 g5370__6131(.A (n_150), .B (n_164), .CO (n_167), .S (n_168));
  OAI2BB1X1 g5371__1881(.A0N (n_157), .A1N (n_162), .B0 (n_165), .Y
       (n_166));
  OR2X1 g5372__5115(.A (n_157), .B (n_162), .Y (n_165));
  CLKXOR2X1 g5373__7482(.A (n_155), .B (n_160), .Y (n_164));
  NOR2BX1 g5374__4733(.AN (n_160), .B (n_161), .Y (n_163));
  NAND2BX1 g5375__6161(.AN (n_155), .B (n_160), .Y (n_162));
  NOR3X1 g5376__9315(.A (n_155), .B (n_157), .C (n_159), .Y (n_161));
  XNOR2X1 g5377__9945(.A (n_14), .B (n_158), .Y (n_160));
  ADDFX1 g5378__2883(.A (A[30]), .B (B[30]), .CI (n_156), .CO (n_158),
       .S (n_159));
  ADDFX1 g5379__2346(.A (A[29]), .B (B[29]), .CI (n_154), .CO (n_156),
       .S (n_157));
  ADDFX1 g5380__1666(.A (A[28]), .B (B[28]), .CI (n_144), .CO (n_154),
       .S (n_155));
  ADDFX1 g5381__7410(.A (n_102), .B (n_127), .CI (n_142), .CO (n_152),
       .S (n_153));
  AND2X1 g5382__6417(.A (n_140), .B (n_147), .Y (n_151));
  OA21X1 g5383__5477(.A0 (n_141), .A1 (n_7), .B0 (n_133), .Y (n_150));
  AND2X1 g5384__2398(.A (n_136), .B (n_146), .Y (n_149));
  AOI21X1 g5385__5107(.A0 (n_133), .A1 (n_6), .B0 (n_7), .Y (n_148));
  NAND3X1 g5386__6260(.A (n_133), .B (n_136), .C (n_145), .Y (n_147));
  NAND3X1 g5387__4319(.A (n_133), .B (n_140), .C (n_145), .Y (n_146));
  ADDFX1 g5389__8428(.A (A[27]), .B (B[27]), .CI (n_139), .CO (n_144),
       .S (n_145));
  ADDFX1 g5390__5526(.A (n_107), .B (n_130), .CI (n_137), .CO (n_142),
       .S (n_143));
  NAND2X1 g5392__6783(.A (n_136), .B (n_140), .Y (n_141));
  ADDFX1 g5393__3680(.A (A[26]), .B (B[26]), .CI (n_135), .CO (n_139),
       .S (n_140));
  ADDFX1 g5394__1617(.A (n_105), .B (n_128), .CI (n_131), .CO (n_137),
       .S (n_138));
  ADDFX1 g5395__2802(.A (A[25]), .B (B[25]), .CI (n_132), .CO (n_135),
       .S (n_136));
  CLKXOR2X1 g5396__1705(.A (n_106), .B (n_129), .Y (n_134));
  ADDFX1 g5397__5122(.A (A[24]), .B (B[24]), .CI (n_123), .CO (n_132),
       .S (n_133));
  NOR2X1 g5398__8246(.A (n_106), .B (n_129), .Y (n_131));
  AND2X1 g5399__7098(.A (n_119), .B (n_126), .Y (n_130));
  OAI2BB1X1 g5400__6131(.A0N (n_120), .A1N (n_124), .B0 (n_111), .Y
       (n_129));
  AND2X1 g5401__1881(.A (n_115), .B (n_125), .Y (n_128));
  AOI21X1 g5402__5115(.A0 (n_111), .A1 (n_120), .B0 (n_5), .Y (n_127));
  NAND3X1 g5403__7482(.A (n_111), .B (n_115), .C (n_124), .Y (n_126));
  NAND3X1 g5404__4733(.A (n_111), .B (n_119), .C (n_124), .Y (n_125));
  ADDFX1 g5406__6161(.A (A[23]), .B (B[23]), .CI (n_118), .CO (n_123),
       .S (n_124));
  ADDFX1 g5407__9315(.A (n_66), .B (n_108), .CI (n_116), .CO (n_121),
       .S (n_122));
  AND2X1 g5408__9945(.A (n_115), .B (n_119), .Y (n_120));
  ADDFX1 g5409__2883(.A (A[22]), .B (B[22]), .CI (n_114), .CO (n_118),
       .S (n_119));
  ADDFX1 g5410__2346(.A (n_67), .B (n_109), .CI (n_112), .CO (n_116),
       .S (n_117));
  ADDFX1 g5411__1666(.A (A[21]), .B (B[21]), .CI (n_110), .CO (n_114),
       .S (n_115));
  ADDFX1 g5412__7410(.A (n_57), .B (n_97), .CI (n_103), .CO (n_112), .S
       (n_113));
  ADDFX1 g5413__6417(.A (A[20]), .B (B[20]), .CI (n_98), .CO (n_110),
       .S (n_111));
  ADDFX1 g5414__5477(.A (n_62), .B (n_79), .CI (n_96), .CO (n_108), .S
       (n_109));
  AND2X1 g5415__2398(.A (n_94), .B (n_101), .Y (n_107));
  OAI2BB1X1 g5416__5107(.A0N (n_95), .A1N (n_99), .B0 (n_85), .Y
       (n_106));
  AND2X1 g5417__6260(.A (n_88), .B (n_100), .Y (n_105));
  ADDFX1 g5418__4319(.A (n_52), .B (n_89), .CI (n_92), .CO (n_103), .S
       (n_104));
  AOI21X1 g5419__8428(.A0 (n_85), .A1 (n_95), .B0 (n_4), .Y (n_102));
  NAND3X1 g5420__5526(.A (n_85), .B (n_88), .C (n_99), .Y (n_101));
  NAND3X1 g5421__6783(.A (n_85), .B (n_94), .C (n_99), .Y (n_100));
  ADDFX1 g5423__3680(.A (A[19]), .B (B[19]), .CI (n_93), .CO (n_98), .S
       (n_99));
  ADDFX1 g5424__1617(.A (n_63), .B (n_82), .CI (n_91), .CO (n_96), .S
       (n_97));
  AND2X1 g5425__2802(.A (n_88), .B (n_94), .Y (n_95));
  ADDFX1 g5426__1705(.A (A[18]), .B (B[18]), .CI (n_87), .CO (n_93), .S
       (n_94));
  ADDFX1 g5427__5122(.A (n_65), .B (n_80), .CI (n_83), .CO (n_91), .S
       (n_92));
  ADDHX1 g5428__8246(.A (n_48), .B (n_86), .CO (n_89), .S (n_90));
  ADDFX1 g5429__7098(.A (A[17]), .B (B[17]), .CI (n_84), .CO (n_87), .S
       (n_88));
  CLKXOR2X1 g5430__6131(.A (n_64), .B (n_81), .Y (n_86));
  ADDFX1 g5431__1881(.A (A[16]), .B (B[16]), .CI (n_75), .CO (n_84), .S
       (n_85));
  NOR2X1 g5432__5115(.A (n_64), .B (n_81), .Y (n_83));
  AND2X1 g5433__7482(.A (n_73), .B (n_78), .Y (n_82));
  OAI2BB1X1 g5434__4733(.A0N (n_74), .A1N (n_76), .B0 (n_69), .Y
       (n_81));
  AND2X1 g5435__6161(.A (n_71), .B (n_77), .Y (n_80));
  AOI21X1 g5436__9315(.A0 (n_69), .A1 (n_74), .B0 (n_3), .Y (n_79));
  NAND3X1 g5437__9945(.A (n_69), .B (n_71), .C (n_76), .Y (n_78));
  NAND3X1 g5438__2883(.A (n_69), .B (n_73), .C (n_76), .Y (n_77));
  ADDFX1 g5440__2346(.A (A[15]), .B (B[15]), .CI (n_72), .CO (n_75), .S
       (n_76));
  AND2X1 g5441__1666(.A (n_71), .B (n_73), .Y (n_74));
  ADDFX1 g5442__7410(.A (A[14]), .B (B[14]), .CI (n_70), .CO (n_72), .S
       (n_73));
  ADDFX1 g5443__6417(.A (A[13]), .B (B[13]), .CI (n_68), .CO (n_70), .S
       (n_71));
  ADDFX1 g5444__5477(.A (A[12]), .B (B[12]), .CI (n_58), .CO (n_68), .S
       (n_69));
  ADDFX1 g5445__2398(.A (n_24), .B (n_41), .CI (n_56), .CO (n_66), .S
       (n_67));
  AND2X1 g5446__5107(.A (n_50), .B (n_61), .Y (n_65));
  OAI2BB1X1 g5447__6260(.A0N (n_55), .A1N (n_59), .B0 (n_47), .Y
       (n_64));
  AND2X1 g5448__4319(.A (n_54), .B (n_60), .Y (n_63));
  AOI21X1 g5449__8428(.A0 (n_47), .A1 (n_55), .B0 (n_2), .Y (n_62));
  NAND3X1 g5450__5526(.A (n_47), .B (n_54), .C (n_59), .Y (n_61));
  NAND3X1 g5451__6783(.A (n_47), .B (n_50), .C (n_59), .Y (n_60));
  ADDFX1 g5453__3680(.A (A[11]), .B (B[11]), .CI (n_53), .CO (n_58), .S
       (n_59));
  ADDFX1 g5454__1617(.A (n_29), .B (n_44), .CI (n_51), .CO (n_56), .S
       (n_57));
  AND2X1 g5455__2802(.A (n_50), .B (n_54), .Y (n_55));
  ADDFX1 g5456__1705(.A (A[10]), .B (B[10]), .CI (n_49), .CO (n_53), .S
       (n_54));
  ADDFX1 g5457__5122(.A (n_28), .B (n_42), .CI (n_45), .CO (n_51), .S
       (n_52));
  ADDFX1 g5458__8246(.A (A[9]), .B (B[9]), .CI (n_46), .CO (n_49), .S
       (n_50));
  CLKXOR2X1 g5459__7098(.A (n_27), .B (n_43), .Y (n_48));
  ADDFX1 g5460__6131(.A (A[8]), .B (B[8]), .CI (n_37), .CO (n_46), .S
       (n_47));
  NOR2X1 g5461__1881(.A (n_27), .B (n_43), .Y (n_45));
  AND2X1 g5462__5115(.A (n_35), .B (n_39), .Y (n_44));
  OAI2BB1X1 g5463__7482(.A0N (n_36), .A1N (n_38), .B0 (n_31), .Y
       (n_43));
  AND2X1 g5464__4733(.A (n_33), .B (n_40), .Y (n_42));
  AOI21X1 g5465__6161(.A0 (n_31), .A1 (n_36), .B0 (n_1), .Y (n_41));
  NAND3X1 g5466__9315(.A (n_31), .B (n_35), .C (n_38), .Y (n_40));
  NAND3X1 g5467__9945(.A (n_31), .B (n_33), .C (n_38), .Y (n_39));
  ADDFX1 g5469__2883(.A (A[7]), .B (B[7]), .CI (n_34), .CO (n_37), .S
       (n_38));
  AND2X1 g5470__2346(.A (n_33), .B (n_35), .Y (n_36));
  ADDFX1 g5471__1666(.A (A[6]), .B (B[6]), .CI (n_32), .CO (n_34), .S
       (n_35));
  ADDFX1 g5472__7410(.A (A[5]), .B (B[5]), .CI (n_30), .CO (n_32), .S
       (n_33));
  ADDFX1 g5473__6417(.A (A[4]), .B (B[4]), .CI (n_22), .CO (n_30), .S
       (n_31));
  AND2X1 g5474__5477(.A (n_20), .B (n_26), .Y (n_29));
  AND2X1 g5475__2398(.A (n_18), .B (n_25), .Y (n_28));
  OAI2BB1X1 g5476__5107(.A0N (n_21), .A1N (n_23), .B0 (n_16), .Y
       (n_27));
  NAND3X1 g5477__6260(.A (n_16), .B (n_18), .C (n_23), .Y (n_26));
  NAND3X1 g5478__4319(.A (n_16), .B (n_20), .C (n_23), .Y (n_25));
  AOI21X1 g5479__8428(.A0 (n_16), .A1 (n_21), .B0 (n_0), .Y (n_24));
  ADDFX1 g5481__5526(.A (A[3]), .B (B[3]), .CI (n_19), .CO (n_22), .S
       (n_23));
  AND2X1 g5482__6783(.A (n_18), .B (n_20), .Y (n_21));
  ADDFX1 g5483__3680(.A (A[2]), .B (B[2]), .CI (n_17), .CO (n_19), .S
       (n_20));
  ADDFX1 g5484__1617(.A (A[1]), .B (B[1]), .CI (n_15), .CO (n_17), .S
       (n_18));
  ADDHX1 g5485__2802(.A (B[0]), .B (A[0]), .CO (n_15), .S (n_16));
  XNOR2X1 g5486__1705(.A (A[31]), .B (B[31]), .Y (n_14));
  INVX1 g5488(.A (n_197), .Y (n_10));
  INVX1 g5490(.A (n_196), .Y (n_9));
  INVX1 g5492(.A (n_208), .Y (n_12));
  INVX1 g5494(.A (n_99), .Y (n_4));
  INVX1 g5496(.A (n_212), .Y (n_13));
  INVX1 g5498(.A (n_59), .Y (n_2));
  INVX1 g5500(.A (n_145), .Y (n_7));
  INVX1 g5502(.A (n_141), .Y (n_6));
  INVX1 g5504(.A (n_204), .Y (n_11));
  INVX1 g5506(.A (n_76), .Y (n_3));
  INVX1 g5508(.A (n_124), .Y (n_5));
  INVX1 g5510(.A (n_38), .Y (n_1));
  INVX1 g5512(.A (n_23), .Y (n_0));
  INVX1 g5514(.A (n_195), .Y (n_8));
endmodule

module mod_flip_flop(clk, rst, A, B, remainder);
  input clk, rst;
  input [31:0] A, B;
  output [3:0] remainder;
  wire clk, rst;
  wire [31:0] A, B;
  wire [3:0] remainder;
  wire [31:0] a_ff;
  wire [31:0] b_ff;
  wire [3:0] remainder_vec;
  wire n_0;
  mod15_n32 adder(.A (a_ff), .B (b_ff), .remainder (remainder_vec));
  DFFRHQX1 \rem_qd_d_reg[3] (.RN (n_0), .CK (clk), .D
       (remainder_vec[3]), .Q (remainder[3]));
  DFFRHQX1 \rem_qd_d_reg[2] (.RN (n_0), .CK (clk), .D
       (remainder_vec[2]), .Q (remainder[2]));
  DFFRHQX1 \rem_qd_d_reg[0] (.RN (n_0), .CK (clk), .D
       (remainder_vec[0]), .Q (remainder[0]));
  DFFRHQX1 \rem_qd_d_reg[1] (.RN (n_0), .CK (clk), .D
       (remainder_vec[1]), .Q (remainder[1]));
  DFFRHQX1 \a_qd_d_reg[2] (.RN (n_0), .CK (clk), .D (A[2]), .Q
       (a_ff[2]));
  DFFRHQX1 \a_qd_d_reg[5] (.RN (n_0), .CK (clk), .D (A[5]), .Q
       (a_ff[5]));
  DFFRHQX1 \b_qd_d_reg[23] (.RN (n_0), .CK (clk), .D (B[23]), .Q
       (b_ff[23]));
  DFFRHQX1 \b_qd_d_reg[6] (.RN (n_0), .CK (clk), .D (B[6]), .Q
       (b_ff[6]));
  DFFRHQX1 \b_qd_d_reg[5] (.RN (n_0), .CK (clk), .D (B[5]), .Q
       (b_ff[5]));
  DFFRHQX1 \b_qd_d_reg[4] (.RN (n_0), .CK (clk), .D (B[4]), .Q
       (b_ff[4]));
  DFFRHQX1 \b_qd_d_reg[29] (.RN (n_0), .CK (clk), .D (B[29]), .Q
       (b_ff[29]));
  DFFRHQX1 \b_qd_d_reg[3] (.RN (n_0), .CK (clk), .D (B[3]), .Q
       (b_ff[3]));
  DFFRHQX1 \b_qd_d_reg[8] (.RN (n_0), .CK (clk), .D (B[8]), .Q
       (b_ff[8]));
  DFFRHQX1 \b_qd_d_reg[2] (.RN (n_0), .CK (clk), .D (B[2]), .Q
       (b_ff[2]));
  DFFRHQX1 \b_qd_d_reg[1] (.RN (n_0), .CK (clk), .D (B[1]), .Q
       (b_ff[1]));
  DFFRHQX1 \b_qd_d_reg[7] (.RN (n_0), .CK (clk), .D (B[7]), .Q
       (b_ff[7]));
  DFFRHQX1 \b_qd_d_reg[12] (.RN (n_0), .CK (clk), .D (B[12]), .Q
       (b_ff[12]));
  DFFRHQX1 \a_qd_d_reg[0] (.RN (n_0), .CK (clk), .D (A[0]), .Q
       (a_ff[0]));
  DFFRHQX1 \a_qd_d_reg[25] (.RN (n_0), .CK (clk), .D (A[25]), .Q
       (a_ff[25]));
  DFFRHQX1 \a_qd_d_reg[1] (.RN (n_0), .CK (clk), .D (A[1]), .Q
       (a_ff[1]));
  DFFRHQX1 \b_qd_d_reg[9] (.RN (n_0), .CK (clk), .D (B[9]), .Q
       (b_ff[9]));
  DFFRHQX1 \b_qd_d_reg[16] (.RN (n_0), .CK (clk), .D (B[16]), .Q
       (b_ff[16]));
  DFFRHQX1 \a_qd_d_reg[21] (.RN (n_0), .CK (clk), .D (A[21]), .Q
       (a_ff[21]));
  DFFRHQX1 \a_qd_d_reg[3] (.RN (n_0), .CK (clk), .D (A[3]), .Q
       (a_ff[3]));
  DFFRHQX1 \a_qd_d_reg[4] (.RN (n_0), .CK (clk), .D (A[4]), .Q
       (a_ff[4]));
  DFFRHQX1 \b_qd_d_reg[0] (.RN (n_0), .CK (clk), .D (B[0]), .Q
       (b_ff[0]));
  DFFRHQX1 \a_qd_d_reg[17] (.RN (n_0), .CK (clk), .D (A[17]), .Q
       (a_ff[17]));
  DFFRHQX1 \a_qd_d_reg[6] (.RN (n_0), .CK (clk), .D (A[6]), .Q
       (a_ff[6]));
  DFFRHQX1 \a_qd_d_reg[7] (.RN (n_0), .CK (clk), .D (A[7]), .Q
       (a_ff[7]));
  DFFRHQX1 \a_qd_d_reg[8] (.RN (n_0), .CK (clk), .D (A[8]), .Q
       (a_ff[8]));
  DFFRHQX1 \a_qd_d_reg[9] (.RN (n_0), .CK (clk), .D (A[9]), .Q
       (a_ff[9]));
  DFFRHQX1 \b_qd_d_reg[24] (.RN (n_0), .CK (clk), .D (B[24]), .Q
       (b_ff[24]));
  DFFRHQX1 \a_qd_d_reg[10] (.RN (n_0), .CK (clk), .D (A[10]), .Q
       (a_ff[10]));
  DFFRHQX1 \a_qd_d_reg[11] (.RN (n_0), .CK (clk), .D (A[11]), .Q
       (a_ff[11]));
  DFFRHQX1 \a_qd_d_reg[12] (.RN (n_0), .CK (clk), .D (A[12]), .Q
       (a_ff[12]));
  DFFRHQX1 \b_qd_d_reg[28] (.RN (n_0), .CK (clk), .D (B[28]), .Q
       (b_ff[28]));
  DFFRHQX1 \b_qd_d_reg[31] (.RN (n_0), .CK (clk), .D (B[31]), .Q
       (b_ff[31]));
  DFFRHQX1 \a_qd_d_reg[14] (.RN (n_0), .CK (clk), .D (A[14]), .Q
       (a_ff[14]));
  DFFRHQX1 \a_qd_d_reg[15] (.RN (n_0), .CK (clk), .D (A[15]), .Q
       (a_ff[15]));
  DFFRHQX1 \a_qd_d_reg[31] (.RN (n_0), .CK (clk), .D (A[31]), .Q
       (a_ff[31]));
  DFFRHQX1 \a_qd_d_reg[16] (.RN (n_0), .CK (clk), .D (A[16]), .Q
       (a_ff[16]));
  DFFRHQX1 \b_qd_d_reg[27] (.RN (n_0), .CK (clk), .D (B[27]), .Q
       (b_ff[27]));
  DFFRHQX1 \a_qd_d_reg[19] (.RN (n_0), .CK (clk), .D (A[19]), .Q
       (a_ff[19]));
  DFFRHQX1 \a_qd_d_reg[20] (.RN (n_0), .CK (clk), .D (A[20]), .Q
       (a_ff[20]));
  DFFRHQX1 \a_qd_d_reg[22] (.RN (n_0), .CK (clk), .D (A[22]), .Q
       (a_ff[22]));
  DFFRHQX1 \a_qd_d_reg[23] (.RN (n_0), .CK (clk), .D (A[23]), .Q
       (a_ff[23]));
  DFFRHQX1 \a_qd_d_reg[24] (.RN (n_0), .CK (clk), .D (A[24]), .Q
       (a_ff[24]));
  DFFRHQX1 \a_qd_d_reg[26] (.RN (n_0), .CK (clk), .D (A[26]), .Q
       (a_ff[26]));
  DFFRHQX1 \a_qd_d_reg[27] (.RN (n_0), .CK (clk), .D (A[27]), .Q
       (a_ff[27]));
  DFFRHQX1 \a_qd_d_reg[28] (.RN (n_0), .CK (clk), .D (A[28]), .Q
       (a_ff[28]));
  DFFRHQX1 \a_qd_d_reg[29] (.RN (n_0), .CK (clk), .D (A[29]), .Q
       (a_ff[29]));
  DFFRHQX1 \a_qd_d_reg[30] (.RN (n_0), .CK (clk), .D (A[30]), .Q
       (a_ff[30]));
  DFFRHQX1 \a_qd_d_reg[13] (.RN (n_0), .CK (clk), .D (A[13]), .Q
       (a_ff[13]));
  DFFRHQX1 \b_qd_d_reg[30] (.RN (n_0), .CK (clk), .D (B[30]), .Q
       (b_ff[30]));
  DFFRHQX1 \a_qd_d_reg[18] (.RN (n_0), .CK (clk), .D (A[18]), .Q
       (a_ff[18]));
  DFFRHQX1 \b_qd_d_reg[26] (.RN (n_0), .CK (clk), .D (B[26]), .Q
       (b_ff[26]));
  DFFRHQX1 \b_qd_d_reg[25] (.RN (n_0), .CK (clk), .D (B[25]), .Q
       (b_ff[25]));
  DFFRHQX1 \b_qd_d_reg[22] (.RN (n_0), .CK (clk), .D (B[22]), .Q
       (b_ff[22]));
  DFFRHQX1 \b_qd_d_reg[21] (.RN (n_0), .CK (clk), .D (B[21]), .Q
       (b_ff[21]));
  DFFRHQX1 \b_qd_d_reg[20] (.RN (n_0), .CK (clk), .D (B[20]), .Q
       (b_ff[20]));
  DFFRHQX1 \b_qd_d_reg[18] (.RN (n_0), .CK (clk), .D (B[18]), .Q
       (b_ff[18]));
  DFFRHQX1 \b_qd_d_reg[17] (.RN (n_0), .CK (clk), .D (B[17]), .Q
       (b_ff[17]));
  DFFRHQX1 \b_qd_d_reg[15] (.RN (n_0), .CK (clk), .D (B[15]), .Q
       (b_ff[15]));
  DFFRHQX1 \b_qd_d_reg[14] (.RN (n_0), .CK (clk), .D (B[14]), .Q
       (b_ff[14]));
  DFFRHQX1 \b_qd_d_reg[13] (.RN (n_0), .CK (clk), .D (B[13]), .Q
       (b_ff[13]));
  DFFRHQX1 \b_qd_d_reg[11] (.RN (n_0), .CK (clk), .D (B[11]), .Q
       (b_ff[11]));
  DFFRHQX1 \b_qd_d_reg[10] (.RN (n_0), .CK (clk), .D (B[10]), .Q
       (b_ff[10]));
  DFFRHQX1 \b_qd_d_reg[19] (.RN (n_0), .CK (clk), .D (B[19]), .Q
       (b_ff[19]));
  INVXL g78(.A (rst), .Y (n_0));
endmodule

