
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Jul  8 2025 14:52:35 EEST (Jul  8 2025 11:52:35 UTC)

// Verification Directory fv/mod_flip_flop 

module mod_flip_flop(clk, rst, A, B, remainder);
  input clk, rst;
  input [31:0] A, B;
  output [3:0] remainder;
  wire clk, rst;
  wire [31:0] A, B;
  wire [3:0] remainder;
  wire [31:0] a_ff;
  wire [31:0] b_ff;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_250, n_251, n_252, n_253, n_254, n_255;
  wire n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  DFFRHQX1 \rem_qd_d_reg[2] (.RN (n_262), .CK (clk), .D (n_261), .Q
       (remainder[2]));
  DFFRHQX1 \rem_qd_d_reg[1] (.RN (n_262), .CK (clk), .D (n_260), .Q
       (remainder[1]));
  XNOR2X1 g5801__2398(.A (n_252), .B (n_259), .Y (n_261));
  DFFRHQX1 \rem_qd_d_reg[3] (.RN (n_262), .CK (clk), .D (n_258), .Q
       (remainder[3]));
  AO21X1 g5805__5107(.A0 (n_256), .A1 (n_257), .B0 (n_259), .Y (n_260));
  OAI22X1 g5804__6260(.A0 (n_255), .A1 (n_254), .B0 (n_257), .B1
       (n_253), .Y (n_258));
  NOR2X1 g5806__4319(.A (n_256), .B (n_257), .Y (n_259));
  NAND2X1 g5807__8428(.A (n_255), .B (n_254), .Y (n_257));
  NOR2BX1 g5808__5526(.AN (n_252), .B (n_256), .Y (n_253));
  OR2X1 g5810__6783(.A (n_217), .B (n_250), .Y (n_256));
  OA21X1 g5809__3680(.A0 (n_249), .A1 (n_202), .B0 (n_251), .Y (n_254));
  AOI221X1 g5811__1617(.A0 (n_223), .A1 (n_215), .B0 (n_246), .B1
       (n_206), .C0 (n_247), .Y (n_251));
  OAI221X1 g5813__2802(.A0 (n_238), .A1 (n_228), .B0 (n_231), .B1
       (n_249), .C0 (n_248), .Y (n_250));
  AOI31X1 g5815__1705(.A0 (n_234), .A1 (n_244), .A2 (n_226), .B0
       (n_245), .Y (n_248));
  AND4X1 g5812__5122(.A (n_200), .B (n_235), .C (n_239), .D (n_242), .Y
       (n_252));
  OAI2BB1X1 g5814__8246(.A0N (n_240), .A1N (n_246), .B0 (n_243), .Y
       (n_247));
  OAI31X1 g5817__7098(.A0 (n_225), .A1 (n_244), .A2 (n_221), .B0
       (n_241), .Y (n_245));
  AOI221X1 g5816__6131(.A0 (n_210), .A1 (n_237), .B0 (n_207), .B1
       (n_224), .C0 (n_197), .Y (n_243));
  AOI221X1 g5818__1881(.A0 (n_194), .A1 (n_236), .B0 (n_201), .B1
       (n_233), .C0 (n_199), .Y (n_242));
  AOI221X1 g5819__5115(.A0 (n_204), .A1 (n_212), .B0 (n_240), .B1
       (n_218), .C0 (n_232), .Y (n_241));
  OA22X1 g5820__7482(.A0 (n_238), .A1 (n_220), .B0 (n_222), .B1
       (n_229), .Y (n_239));
  OR2X1 g5821__4733(.A (n_236), .B (n_227), .Y (n_237));
  AOI32X1 g5823__6161(.A0 (n_234), .A1 (n_246), .A2 (n_214), .B0
       (n_188), .B1 (n_213), .Y (n_235));
  OAI22X1 g5827__9315(.A0 (n_216), .A1 (n_219), .B0 (n_189), .B1
       (n_230), .Y (n_233));
  OAI31X1 g5822__9945(.A0 (n_231), .A1 (n_246), .A2 (n_230), .B0
       (n_193), .Y (n_232));
  OA21X1 g5824__2883(.A0 (n_211), .A1 (n_230), .B0 (n_228), .Y (n_229));
  NOR3BX1 g5826__2346(.AN (n_226), .B (n_225), .C (n_240), .Y (n_227));
  OAI22X1 g5828__1666(.A0 (n_223), .A1 (n_203), .B0 (n_222), .B1
       (n_221), .Y (n_224));
  AND2X1 g5830__7410(.A (n_219), .B (n_218), .Y (n_220));
  OAI31X1 g5825__6417(.A0 (n_195), .A1 (n_221), .A2 (n_216), .B0
       (n_209), .Y (n_217));
  AO22X1 g5829__5477(.A0 (n_190), .A1 (n_214), .B0 (n_208), .B1
       (n_191), .Y (n_215));
  NOR2X1 g5831__2398(.A (n_238), .B (n_230), .Y (n_213));
  NAND2X1 g5832__5107(.A (n_216), .B (n_214), .Y (n_228));
  AO21X1 g5834__6260(.A0 (n_211), .A1 (n_198), .B0 (n_210), .Y (n_212));
  INVX1 g5839(.A (n_226), .Y (n_219));
  OR4X1 g5836__4319(.A (n_184), .B (n_208), .C (n_207), .D (n_205), .Y
       (n_209));
  AO21X1 g5835__8428(.A0 (n_196), .A1 (n_205), .B0 (n_204), .Y (n_206));
  INVX1 g5838(.A (n_214), .Y (n_203));
  XNOR2X1 g5837__5526(.A (n_201), .B (n_205), .Y (n_202));
  NOR3X1 g5833__6783(.A (n_201), .B (n_240), .C (n_205), .Y (n_236));
  OAI211X1 g5843__3680(.A0 (n_208), .A1 (n_246), .B0 (n_223), .C0
       (n_205), .Y (n_200));
  AOI211XL g5844__1617(.A0 (n_208), .A1 (n_244), .B0 (n_231), .C0
       (n_205), .Y (n_199));
  NAND2X1 g5840__2802(.A (n_246), .B (n_198), .Y (n_218));
  AND2X1 g5842__1705(.A (n_208), .B (n_198), .Y (n_226));
  OR2X1 g5845__5122(.A (n_208), .B (n_198), .Y (n_230));
  AND2X1 g5841__8246(.A (n_208), .B (n_205), .Y (n_214));
  INVX1 g5846(.A (n_205), .Y (n_198));
  NOR2X1 g5848__7098(.A (n_238), .B (n_249), .Y (n_197));
  ADDHX1 g5847__6131(.A (n_154), .B (n_192), .CO (n_240), .S (n_205));
  OAI21X1 g5849__1881(.A0 (n_195), .A1 (n_208), .B0 (n_183), .Y
       (n_196));
  INVX1 g5851(.A (n_249), .Y (n_194));
  NAND3X1 g5852__5115(.A (n_195), .B (n_221), .C (n_246), .Y (n_193));
  NOR2X1 g5850__7482(.A (n_222), .B (n_208), .Y (n_204));
  OR2X1 g5853__4733(.A (n_208), .B (n_244), .Y (n_249));
  INVX1 g5854(.A (n_221), .Y (n_208));
  ADDFX1 g5855__6161(.A (n_155), .B (n_180), .CI (n_185), .CO (n_192),
       .S (n_221));
  OR2X1 g5856__9315(.A (n_191), .B (n_190), .Y (n_210));
  INVX1 g5858(.A (n_246), .Y (n_216));
  INVX1 g5861(.A (n_191), .Y (n_189));
  INVX1 g5857(.A (n_244), .Y (n_207));
  NOR2X1 g5863__9945(.A (n_188), .B (n_187), .Y (n_191));
  AND2XL g5860__2883(.A (n_186), .B (n_187), .Y (n_246));
  NAND2X1 g5859__2346(.A (n_188), .B (n_211), .Y (n_244));
  NOR2X1 g5862__1666(.A (n_186), .B (n_211), .Y (n_190));
  INVX1 g5864(.A (n_211), .Y (n_187));
  ADDFX1 g5865__7410(.A (n_145), .B (n_181), .CI (n_182), .CO (n_185),
       .S (n_211));
  INVX1 g5868(.A (n_223), .Y (n_184));
  OR2X1 g5866__6417(.A (n_195), .B (n_183), .Y (n_222));
  OR2X1 g5867__5477(.A (n_225), .B (n_183), .Y (n_238));
  INVX1 g5869(.A (n_231), .Y (n_234));
  AND2X1 g5870__2398(.A (n_195), .B (n_183), .Y (n_223));
  OR2X1 g5871__5107(.A (n_195), .B (n_201), .Y (n_231));
  INVX1 g5872(.A (n_201), .Y (n_183));
  ADDFX1 g5873__6260(.A (n_140), .B (n_178), .CI (n_179), .CO (n_182),
       .S (n_201));
  ADDHX1 g5874__4319(.A (n_170), .B (n_177), .CO (n_180), .S (n_181));
  INVX1 g5875(.A (n_225), .Y (n_195));
  ADDFX1 g5876__8428(.A (n_137), .B (n_176), .CI (n_174), .CO (n_179),
       .S (n_225));
  ADDFX1 g5877__5526(.A (n_165), .B (n_171), .CI (n_175), .CO (n_177),
       .S (n_178));
  INVX1 g5878(.A (n_188), .Y (n_186));
  ADDHX1 g5879__6783(.A (n_123), .B (n_172), .CO (n_176), .S (n_188));
  AOI2BB1X1 g5880__3680(.A0N (n_168), .A1N (n_173), .B0 (n_167), .Y
       (n_175));
  CLKXOR2X1 g5881__1617(.A (n_173), .B (n_169), .Y (n_174));
  ADDHX1 g5883__2802(.A (n_156), .B (n_166), .CO (n_173), .S (n_172));
  ADDFX1 g5882__1705(.A (n_133), .B (n_151), .CI (n_164), .CO (n_170),
       .S (n_171));
  XNOR2X1 g5885__5122(.A (n_168), .B (n_167), .Y (n_169));
  ADDHX1 g5886__8246(.A (n_158), .B (n_165), .CO (n_168), .S (n_166));
  OAI22X1 g5888__7098(.A0 (n_163), .A1 (n_161), .B0 (n_160), .B1
       (n_159), .Y (n_164));
  CLKXOR2X1 g5889__6131(.A (n_163), .B (n_162), .Y (n_167));
  XNOR2X1 g5892__1881(.A (n_0), .B (n_157), .Y (n_165));
  ADDHX1 g5890__5115(.A (n_160), .B (n_159), .CO (n_161), .S (n_162));
  ADDFX1 g5894__7482(.A (a_ff[30]), .B (b_ff[30]), .CI (n_146), .CO
       (n_157), .S (n_158));
  CLKXOR2X1 g5893__4733(.A (n_153), .B (n_152), .Y (n_156));
  ADDFX1 g5884__6161(.A (n_73), .B (n_141), .CI (n_144), .CO (n_154),
       .S (n_155));
  OR2X1 g5895__9315(.A (n_153), .B (n_152), .Y (n_163));
  OAI2BB1X1 g5897__9945(.A0N (n_150), .A1N (n_148), .B0 (n_149), .Y
       (n_159));
  AOI21X1 g5899__2883(.A0 (n_150), .A1 (n_149), .B0 (n_147), .Y
       (n_151));
  OAI2BB1X1 g5898__2346(.A0N (n_149), .A1N (n_148), .B0 (n_150), .Y
       (n_152));
  INVX1 g5900(.A (n_148), .Y (n_147));
  ADDFX1 g5902__1666(.A (a_ff[29]), .B (b_ff[29]), .CI (n_143), .CO
       (n_146), .S (n_148));
  ADDFX1 g5887__7410(.A (n_74), .B (n_142), .CI (n_139), .CO (n_144),
       .S (n_145));
  ADDFX1 g5904__6417(.A (a_ff[28]), .B (b_ff[28]), .CI (n_138), .CO
       (n_143), .S (n_149));
  ADDFX1 g5896__5477(.A (n_93), .B (n_124), .CI (n_134), .CO (n_141),
       .S (n_142));
  ADDFX1 g5891__2398(.A (n_71), .B (n_135), .CI (n_136), .CO (n_139),
       .S (n_140));
  ADDFX1 g5906__5107(.A (a_ff[27]), .B (b_ff[27]), .CI (n_128), .CO
       (n_138), .S (n_150));
  ADDFX1 g5901__6260(.A (n_62), .B (n_122), .CI (n_127), .CO (n_136),
       .S (n_137));
  ADDFX1 g5903__4319(.A (n_94), .B (n_125), .CI (n_126), .CO (n_134),
       .S (n_135));
  OAI2BB1X1 g5909__8428(.A0N (n_132), .A1N (n_130), .B0 (n_131), .Y
       (n_160));
  AOI21X1 g5911__5526(.A0 (n_132), .A1 (n_131), .B0 (n_129), .Y
       (n_133));
  OAI2BB1X1 g5910__6783(.A0N (n_131), .A1N (n_130), .B0 (n_132), .Y
       (n_153));
  INVX1 g5912(.A (n_130), .Y (n_129));
  ADDFX1 g5913__3680(.A (a_ff[26]), .B (b_ff[26]), .CI (n_121), .CO
       (n_128), .S (n_130));
  ADDFX1 g5905__1617(.A (n_90), .B (n_117), .CI (n_120), .CO (n_126),
       .S (n_127));
  ADDFX1 g5907__2802(.A (n_100), .B (n_110), .CI (n_119), .CO (n_124),
       .S (n_125));
  ADDHX1 g5908__1705(.A (n_54), .B (n_118), .CO (n_122), .S (n_123));
  ADDFX1 g5916__5122(.A (a_ff[25]), .B (b_ff[25]), .CI (n_116), .CO
       (n_121), .S (n_131));
  ADDFX1 g5914__8246(.A (n_101), .B (n_111), .CI (n_114), .CO (n_119),
       .S (n_120));
  ADDHX1 g5915__7098(.A (n_87), .B (n_115), .CO (n_117), .S (n_118));
  ADDFX1 g5918__6131(.A (a_ff[24]), .B (b_ff[24]), .CI (n_105), .CO
       (n_116), .S (n_132));
  CLKXOR2X1 g5917__1881(.A (n_113), .B (n_112), .Y (n_115));
  NOR2X1 g5919__5115(.A (n_113), .B (n_112), .Y (n_114));
  AOI21X1 g5920__7482(.A0 (n_109), .A1 (n_107), .B0 (n_104), .Y
       (n_111));
  AOI21X1 g5922__4733(.A0 (n_109), .A1 (n_108), .B0 (n_106), .Y
       (n_110));
  OAI2BB1X1 g5921__6161(.A0N (n_108), .A1N (n_107), .B0 (n_109), .Y
       (n_112));
  INVX1 g5923(.A (n_107), .Y (n_106));
  ADDFX1 g5924__9315(.A (a_ff[23]), .B (b_ff[23]), .CI (n_103), .CO
       (n_105), .S (n_107));
  INVX1 g5925(.A (n_108), .Y (n_104));
  ADDFX1 g5926__9945(.A (a_ff[22]), .B (b_ff[22]), .CI (n_102), .CO
       (n_103), .S (n_108));
  ADDFX1 g5927__2883(.A (a_ff[21]), .B (b_ff[21]), .CI (n_95), .CO
       (n_102), .S (n_109));
  AOI21X1 g5929__2346(.A0 (n_99), .A1 (n_97), .B0 (n_92), .Y (n_101));
  AOI21X1 g5931__1666(.A0 (n_99), .A1 (n_98), .B0 (n_96), .Y (n_100));
  OAI2BB1X1 g5930__7410(.A0N (n_98), .A1N (n_97), .B0 (n_99), .Y
       (n_113));
  INVX1 g5932(.A (n_97), .Y (n_96));
  ADDFX1 g5933__6417(.A (a_ff[20]), .B (b_ff[20]), .CI (n_91), .CO
       (n_95), .S (n_97));
  ADDFX1 g5928__5477(.A (n_66), .B (n_82), .CI (n_89), .CO (n_93), .S
       (n_94));
  INVX1 g5935(.A (n_98), .Y (n_92));
  ADDFX1 g5936__2398(.A (a_ff[19]), .B (b_ff[19]), .CI (n_88), .CO
       (n_91), .S (n_98));
  ADDFX1 g5934__5107(.A (n_69), .B (n_83), .CI (n_86), .CO (n_89), .S
       (n_90));
  ADDFX1 g5938__6260(.A (a_ff[18]), .B (b_ff[18]), .CI (n_77), .CO
       (n_88), .S (n_99));
  CLKXOR2X1 g5937__4319(.A (n_85), .B (n_84), .Y (n_87));
  NOR2X1 g5939__8428(.A (n_85), .B (n_84), .Y (n_86));
  AOI21X1 g5941__5526(.A0 (n_81), .A1 (n_79), .B0 (n_76), .Y (n_83));
  AOI21X1 g5943__6783(.A0 (n_81), .A1 (n_80), .B0 (n_78), .Y (n_82));
  OAI2BB1X1 g5942__3680(.A0N (n_80), .A1N (n_79), .B0 (n_81), .Y
       (n_84));
  INVX1 g5944(.A (n_79), .Y (n_78));
  ADDFX1 g5945__1617(.A (a_ff[17]), .B (b_ff[17]), .CI (n_75), .CO
       (n_77), .S (n_79));
  INVX1 g5947(.A (n_80), .Y (n_76));
  ADDFX1 g5948__2802(.A (a_ff[16]), .B (b_ff[16]), .CI (n_72), .CO
       (n_75), .S (n_80));
  ADDFX1 g5940__1705(.A (n_29), .B (n_59), .CI (n_70), .CO (n_73), .S
       (n_74));
  ADDFX1 g5950__5122(.A (a_ff[15]), .B (b_ff[15]), .CI (n_63), .CO
       (n_72), .S (n_81));
  ADDFX1 g5946__8246(.A (n_30), .B (n_60), .CI (n_61), .CO (n_70), .S
       (n_71));
  OAI2BB1X1 g5952__7098(.A0N (n_65), .A1N (n_67), .B0 (n_68), .Y
       (n_85));
  AOI21X1 g5953__6131(.A0 (n_68), .A1 (n_67), .B0 (n_58), .Y (n_69));
  AOI21X1 g5954__1881(.A0 (n_68), .A1 (n_65), .B0 (n_64), .Y (n_66));
  INVX1 g5955(.A (n_67), .Y (n_64));
  ADDFX1 g5956__5115(.A (a_ff[14]), .B (b_ff[14]), .CI (n_57), .CO
       (n_63), .S (n_67));
  ADDFX1 g5949__7482(.A (n_26), .B (n_53), .CI (n_56), .CO (n_61), .S
       (n_62));
  ADDFX1 g5951__4733(.A (n_36), .B (n_46), .CI (n_55), .CO (n_59), .S
       (n_60));
  INVX1 g5959(.A (n_65), .Y (n_58));
  ADDFX1 g5960__6161(.A (a_ff[13]), .B (b_ff[13]), .CI (n_52), .CO
       (n_57), .S (n_65));
  ADDFX1 g5957__9315(.A (n_37), .B (n_47), .CI (n_50), .CO (n_55), .S
       (n_56));
  ADDHX1 g5958__9945(.A (n_23), .B (n_51), .CO (n_53), .S (n_54));
  ADDFX1 g5962__2883(.A (a_ff[12]), .B (b_ff[12]), .CI (n_41), .CO
       (n_52), .S (n_68));
  CLKXOR2X1 g5961__2346(.A (n_49), .B (n_48), .Y (n_51));
  NOR2X1 g5963__1666(.A (n_49), .B (n_48), .Y (n_50));
  AOI21X1 g5964__7410(.A0 (n_45), .A1 (n_43), .B0 (n_40), .Y (n_47));
  AOI21X1 g5966__6417(.A0 (n_45), .A1 (n_44), .B0 (n_42), .Y (n_46));
  OAI2BB1X1 g5965__5477(.A0N (n_44), .A1N (n_43), .B0 (n_45), .Y
       (n_48));
  INVX1 g5967(.A (n_43), .Y (n_42));
  ADDFX1 g5968__2398(.A (a_ff[11]), .B (b_ff[11]), .CI (n_39), .CO
       (n_41), .S (n_43));
  INVX1 g5969(.A (n_44), .Y (n_40));
  ADDFX1 g5970__5107(.A (a_ff[10]), .B (b_ff[10]), .CI (n_38), .CO
       (n_39), .S (n_44));
  ADDFX1 g5971__6260(.A (a_ff[9]), .B (b_ff[9]), .CI (n_31), .CO
       (n_38), .S (n_45));
  AOI21X1 g5973__4319(.A0 (n_35), .A1 (n_33), .B0 (n_28), .Y (n_37));
  AOI21X1 g5975__8428(.A0 (n_35), .A1 (n_34), .B0 (n_32), .Y (n_36));
  OAI2BB1X1 g5974__5526(.A0N (n_34), .A1N (n_33), .B0 (n_35), .Y
       (n_49));
  INVX1 g5976(.A (n_33), .Y (n_32));
  ADDFX1 g5977__6783(.A (a_ff[8]), .B (b_ff[8]), .CI (n_27), .CO
       (n_31), .S (n_33));
  ADDFX1 g5972__3680(.A (n_7), .B (n_18), .CI (n_25), .CO (n_29), .S
       (n_30));
  INVX1 g5979(.A (n_34), .Y (n_28));
  ADDFX1 g5980__1617(.A (a_ff[7]), .B (b_ff[7]), .CI (n_24), .CO
       (n_27), .S (n_34));
  ADDFX1 g5978__2802(.A (n_9), .B (n_19), .CI (n_22), .CO (n_25), .S
       (n_26));
  ADDFX1 g5982__1705(.A (a_ff[6]), .B (b_ff[6]), .CI (n_13), .CO
       (n_24), .S (n_35));
  CLKXOR2X1 g5981__5122(.A (n_21), .B (n_20), .Y (n_23));
  NOR2X1 g5983__8246(.A (n_21), .B (n_20), .Y (n_22));
  AOI21X1 g5984__7098(.A0 (n_17), .A1 (n_15), .B0 (n_12), .Y (n_19));
  AOI21X1 g5986__6131(.A0 (n_17), .A1 (n_16), .B0 (n_14), .Y (n_18));
  OAI2BB1X1 g5985__1881(.A0N (n_16), .A1N (n_15), .B0 (n_17), .Y
       (n_20));
  INVX1 g5987(.A (n_15), .Y (n_14));
  ADDFX1 g5988__5115(.A (a_ff[5]), .B (b_ff[5]), .CI (n_11), .CO
       (n_13), .S (n_15));
  INVX1 g5989(.A (n_16), .Y (n_12));
  ADDFX1 g5990__7482(.A (a_ff[4]), .B (b_ff[4]), .CI (n_10), .CO
       (n_11), .S (n_16));
  ADDFX1 g5991__4733(.A (a_ff[3]), .B (b_ff[3]), .CI (n_5), .CO (n_10),
       .S (n_17));
  AOI21X1 g5992__6161(.A0 (n_255), .A1 (n_8), .B0 (n_6), .Y (n_9));
  OAI2BB1X1 g5993__9315(.A0N (n_4), .A1N (n_8), .B0 (n_255), .Y (n_21));
  OA21X1 g5994__9945(.A0 (n_2), .A1 (n_6), .B0 (n_8), .Y (n_7));
  ADDFX1 g5995__2883(.A (a_ff[2]), .B (b_ff[2]), .CI (n_3), .CO (n_5),
       .S (n_8));
  INVX1 g5996(.A (n_4), .Y (n_6));
  ADDFX1 g5997__2346(.A (a_ff[1]), .B (b_ff[1]), .CI (n_1), .CO (n_3),
       .S (n_4));
  DFFRHQX1 \rem_qd_d_reg[0] (.RN (n_262), .CK (clk), .D (n_255), .Q
       (remainder[0]));
  INVX1 g5999(.A (n_255), .Y (n_2));
  ADDHX1 g6000__1666(.A (b_ff[0]), .B (a_ff[0]), .CO (n_1), .S (n_255));
  XNOR2X1 g6001__7410(.A (a_ff[31]), .B (b_ff[31]), .Y (n_0));
  DFFRHQX1 \a_qd_d_reg[10] (.RN (n_262), .CK (clk), .D (A[10]), .Q
       (a_ff[10]));
  DFFRHQX1 \a_qd_d_reg[27] (.RN (n_262), .CK (clk), .D (A[27]), .Q
       (a_ff[27]));
  DFFRHQX1 \a_qd_d_reg[9] (.RN (n_262), .CK (clk), .D (A[9]), .Q
       (a_ff[9]));
  DFFRHQX1 \a_qd_d_reg[20] (.RN (n_262), .CK (clk), .D (A[20]), .Q
       (a_ff[20]));
  DFFRHQX1 \a_qd_d_reg[26] (.RN (n_262), .CK (clk), .D (A[26]), .Q
       (a_ff[26]));
  DFFRHQX1 \a_qd_d_reg[29] (.RN (n_262), .CK (clk), .D (A[29]), .Q
       (a_ff[29]));
  DFFRHQX1 \a_qd_d_reg[14] (.RN (n_262), .CK (clk), .D (A[14]), .Q
       (a_ff[14]));
  DFFRHQX1 \b_qd_d_reg[15] (.RN (n_262), .CK (clk), .D (B[15]), .Q
       (b_ff[15]));
  DFFRHQX1 \a_qd_d_reg[23] (.RN (n_262), .CK (clk), .D (A[23]), .Q
       (a_ff[23]));
  DFFRHQX1 \b_qd_d_reg[0] (.RN (n_262), .CK (clk), .D (B[0]), .Q
       (b_ff[0]));
  DFFRHQX1 \b_qd_d_reg[22] (.RN (n_262), .CK (clk), .D (B[22]), .Q
       (b_ff[22]));
  DFFRHQX1 \a_qd_d_reg[4] (.RN (n_262), .CK (clk), .D (A[4]), .Q
       (a_ff[4]));
  DFFRHQX1 \a_qd_d_reg[17] (.RN (n_262), .CK (clk), .D (A[17]), .Q
       (a_ff[17]));
  DFFRHQX1 \a_qd_d_reg[15] (.RN (n_262), .CK (clk), .D (A[15]), .Q
       (a_ff[15]));
  DFFRHQX1 \a_qd_d_reg[19] (.RN (n_262), .CK (clk), .D (A[19]), .Q
       (a_ff[19]));
  DFFRHQX1 \b_qd_d_reg[25] (.RN (n_262), .CK (clk), .D (B[25]), .Q
       (b_ff[25]));
  DFFRHQX1 \b_qd_d_reg[13] (.RN (n_262), .CK (clk), .D (B[13]), .Q
       (b_ff[13]));
  DFFRHQX1 \a_qd_d_reg[31] (.RN (n_262), .CK (clk), .D (A[31]), .Q
       (a_ff[31]));
  DFFRHQX1 \b_qd_d_reg[4] (.RN (n_262), .CK (clk), .D (B[4]), .Q
       (b_ff[4]));
  DFFRHQX1 \a_qd_d_reg[2] (.RN (n_262), .CK (clk), .D (A[2]), .Q
       (a_ff[2]));
  DFFRHQX1 \a_qd_d_reg[3] (.RN (n_262), .CK (clk), .D (A[3]), .Q
       (a_ff[3]));
  DFFRHQX1 \b_qd_d_reg[17] (.RN (n_262), .CK (clk), .D (B[17]), .Q
       (b_ff[17]));
  DFFRHQX1 \b_qd_d_reg[18] (.RN (n_262), .CK (clk), .D (B[18]), .Q
       (b_ff[18]));
  DFFRHQX1 \b_qd_d_reg[29] (.RN (n_262), .CK (clk), .D (B[29]), .Q
       (b_ff[29]));
  DFFRHQX1 \b_qd_d_reg[23] (.RN (n_262), .CK (clk), .D (B[23]), .Q
       (b_ff[23]));
  DFFRHQX1 \a_qd_d_reg[28] (.RN (n_262), .CK (clk), .D (A[28]), .Q
       (a_ff[28]));
  DFFRHQX1 \b_qd_d_reg[12] (.RN (n_262), .CK (clk), .D (B[12]), .Q
       (b_ff[12]));
  DFFRHQX1 \a_qd_d_reg[6] (.RN (n_262), .CK (clk), .D (A[6]), .Q
       (a_ff[6]));
  DFFRHQX1 \b_qd_d_reg[24] (.RN (n_262), .CK (clk), .D (B[24]), .Q
       (b_ff[24]));
  DFFRHQX1 \b_qd_d_reg[2] (.RN (n_262), .CK (clk), .D (B[2]), .Q
       (b_ff[2]));
  DFFRHQX1 \b_qd_d_reg[26] (.RN (n_262), .CK (clk), .D (B[26]), .Q
       (b_ff[26]));
  DFFRHQX1 \a_qd_d_reg[0] (.RN (n_262), .CK (clk), .D (A[0]), .Q
       (a_ff[0]));
  DFFRHQX1 \b_qd_d_reg[9] (.RN (n_262), .CK (clk), .D (B[9]), .Q
       (b_ff[9]));
  DFFRHQX1 \a_qd_d_reg[1] (.RN (n_262), .CK (clk), .D (A[1]), .Q
       (a_ff[1]));
  DFFRHQX1 \a_qd_d_reg[22] (.RN (n_262), .CK (clk), .D (A[22]), .Q
       (a_ff[22]));
  DFFRHQX1 \a_qd_d_reg[16] (.RN (n_262), .CK (clk), .D (A[16]), .Q
       (a_ff[16]));
  DFFRHQX1 \b_qd_d_reg[3] (.RN (n_262), .CK (clk), .D (B[3]), .Q
       (b_ff[3]));
  DFFRHQX1 \b_qd_d_reg[21] (.RN (n_262), .CK (clk), .D (B[21]), .Q
       (b_ff[21]));
  DFFRHQX1 \a_qd_d_reg[18] (.RN (n_262), .CK (clk), .D (A[18]), .Q
       (a_ff[18]));
  DFFRHQX1 \b_qd_d_reg[31] (.RN (n_262), .CK (clk), .D (B[31]), .Q
       (b_ff[31]));
  DFFRHQX1 \b_qd_d_reg[14] (.RN (n_262), .CK (clk), .D (B[14]), .Q
       (b_ff[14]));
  DFFRHQX1 \a_qd_d_reg[25] (.RN (n_262), .CK (clk), .D (A[25]), .Q
       (a_ff[25]));
  DFFRHQX1 \a_qd_d_reg[5] (.RN (n_262), .CK (clk), .D (A[5]), .Q
       (a_ff[5]));
  DFFRHQX1 \b_qd_d_reg[1] (.RN (n_262), .CK (clk), .D (B[1]), .Q
       (b_ff[1]));
  DFFRHQX1 \a_qd_d_reg[13] (.RN (n_262), .CK (clk), .D (A[13]), .Q
       (a_ff[13]));
  DFFRHQX1 \b_qd_d_reg[11] (.RN (n_262), .CK (clk), .D (B[11]), .Q
       (b_ff[11]));
  DFFRHQX1 \a_qd_d_reg[8] (.RN (n_262), .CK (clk), .D (A[8]), .Q
       (a_ff[8]));
  DFFRHQX1 \a_qd_d_reg[7] (.RN (n_262), .CK (clk), .D (A[7]), .Q
       (a_ff[7]));
  DFFRHQX1 \a_qd_d_reg[12] (.RN (n_262), .CK (clk), .D (A[12]), .Q
       (a_ff[12]));
  DFFRHQX1 \b_qd_d_reg[8] (.RN (n_262), .CK (clk), .D (B[8]), .Q
       (b_ff[8]));
  DFFRHQX1 \a_qd_d_reg[30] (.RN (n_262), .CK (clk), .D (A[30]), .Q
       (a_ff[30]));
  DFFRHQX1 \a_qd_d_reg[24] (.RN (n_262), .CK (clk), .D (A[24]), .Q
       (a_ff[24]));
  DFFRHQX1 \a_qd_d_reg[11] (.RN (n_262), .CK (clk), .D (A[11]), .Q
       (a_ff[11]));
  DFFRHQX1 \b_qd_d_reg[20] (.RN (n_262), .CK (clk), .D (B[20]), .Q
       (b_ff[20]));
  DFFRHQX1 \b_qd_d_reg[16] (.RN (n_262), .CK (clk), .D (B[16]), .Q
       (b_ff[16]));
  DFFRHQX1 \a_qd_d_reg[21] (.RN (n_262), .CK (clk), .D (A[21]), .Q
       (a_ff[21]));
  DFFRHQX1 \b_qd_d_reg[28] (.RN (n_262), .CK (clk), .D (B[28]), .Q
       (b_ff[28]));
  DFFRHQX1 \b_qd_d_reg[5] (.RN (n_262), .CK (clk), .D (B[5]), .Q
       (b_ff[5]));
  DFFRHQX1 \b_qd_d_reg[6] (.RN (n_262), .CK (clk), .D (B[6]), .Q
       (b_ff[6]));
  DFFRHQX1 \b_qd_d_reg[19] (.RN (n_262), .CK (clk), .D (B[19]), .Q
       (b_ff[19]));
  DFFRHQX1 \b_qd_d_reg[27] (.RN (n_262), .CK (clk), .D (B[27]), .Q
       (b_ff[27]));
  DFFRHQX1 \b_qd_d_reg[7] (.RN (n_262), .CK (clk), .D (B[7]), .Q
       (b_ff[7]));
  DFFRHQX1 \b_qd_d_reg[10] (.RN (n_262), .CK (clk), .D (B[10]), .Q
       (b_ff[10]));
  DFFRHQX1 \b_qd_d_reg[30] (.RN (n_262), .CK (clk), .D (B[30]), .Q
       (b_ff[30]));
  INVXL g6066(.A (rst), .Y (n_262));
endmodule

